name: main

on:
  push:
    paths:
        - inputs/*.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0 # Recommended with tj-actions/changed-files to properly compare commits

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5

    - name: Convert to JSON
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }} 
      run: |
        # Ensure the destination directory exists
        mkdir -p changelog
        
        # Get the date once in YYYY-MM-DD_HH-MM format
        current_date=$(date +"%F_%H-%M")
        
        for file in ${CHANGED_FILES}; do

          # 1. Isolate the full name (e.g., myfile.txt)
          base_name=$(basename "$file")

          # 2. Remove the extension (e.g., myfile)
          name_no_ext="${base_name%.*}"
          
          # Build the final file path
          json_file="changelog/${current_date}_${name_no_ext}.json"
          
          # Convert text to JSON array with jq
          jq -Rn '[inputs | select(test("\\S"))]' "$file" > "$json_file"
          
          # Log the result in GitHub Actions
          echo "Generated file: $json_file"
          cat "$json_file"

          # Merge the new array into the main file and keep unique entries
          # Using a temporary file to avoid in-place overwrite issues with jq
          jq -s 'add | unique' flashed-invaders.json "$json_file" > tmp.json
          mv tmp.json flashed-invaders.json
        done